name: CI
on: [push, pull_request]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml]
        
    - name: Run Bandit Scan
      run: |
        bandit -ll -ii -r . -f json -o bandit-report.json || true
        
    - name: Display Bandit Results
      run: |
        if [ -f bandit-report.json ]; then
          echo "Bandit scan completed. Report generated."
          bandit -ll -ii -r . -f txt || true
        else
          echo "No bandit report generated"
        fi
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
        retention-days: 30

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REPO_USER }}
        password: ${{ secrets.REPO_PWD }}
        
    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: myapp:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Docker Scout Scan
      uses: docker/scout-action@v1.13.0
      with:
        command: quickview,cves
        image: myapp:latest
        only-severities: critical,high
        sarif-file: scout-report.sarif
        exit-code: false
        
    - name: Display Scout Results
      run: |
        if [ -f scout-report.sarif ]; then
          echo "Docker Scout scan completed. SARIF report generated."
          echo "Checking for critical/high vulnerabilities..."
        else
          echo "No Docker Scout report generated"
        fi
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-scout-findings-${{ github.run_number }}
        path: scout-report.sarif
        retention-days: 30